# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            soon online
tagline:          '#tivolevodire'
description:      'follow me on <a href="https://twitter.com/dbresciani" target="_blank">twitter</a>.'

author:
  name:           'db'
  url:            https://twitter.com/dbresciani

paginate:         5

# Custom vars
version:          1.0.0
